name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Transfer files to the EC2 instance
          scp -o StrictHostKeyChecking=no -i $SSH_KEY -r ./build ec2-user@$INSTANCE_IP:/tmp/build
      
          # SSH into EC2 and move files to the appropriate directory
          ssh -o StrictHostKeyChecking=no -i $SSH_KEY ec2-user@$INSTANCE_IP << 'EOF'
            sudo rm -rf /var/www/html/*
            sudo mv /tmp/build/* /var/www/html/
            sudo chown -R nginx:nginx /var/www/html
            sudo systemctl restart nginx
          EOF

