name: Deploy Backend to EC2

on:
  push:
    branches:
      - main # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Specify the Node.js version

      - name: Install Dependencies for Node.js
        run: |
          npm install

      - name: Copy Files to EC2
        run: |
          scp -i /tmp/my-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./* ec2-user@YOUR_INSTANCE_IP:/backend/

      - name: Deploy Node.js Backend
        run: |
          ssh -i /tmp/my-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@YOUR_INSTANCE_IP "cd /backend && npm install && pm2 restart my-backend-app || pm2 start app.js --name my-backend-app"

      - name: Clean Up
        run: |
          rm -f /tmp/my-key.pem
