name: Deploy Backend to EC2

on:
  push:
    branches:
      - main # Change this to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Specify the Node.js version

      - name: Install Dependencies for Node.js
        run: |
          npm install

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Save the SSH key to a temporary file
          echo "$SSH_KEY" > /tmp/my-key.pem
          chmod 600 /tmp/my-key.pem


          # Check if the build directory exists before transferring
          if [ -d "./packages/api-gateway" ]; then
            # Transfer files to the EC2 instance
            scp -o StrictHostKeyChecking=no -i /tmp/my-key.pem -r ./* ec2-user@$INSTANCE_IP:/var/www/html/
          else
            echo "Directory not found!"
            exit 1  # Exit with an error if the build directory does not exist
          fi

          # SSH into EC2 and restart the backend server
          ssh -i /tmp/my-key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@$INSTANCE_IP "cd /var/www/html/ && npm install && pm2 restart my-backend-app || pm2 start app.js --name my-backend-app"

          # Cleanup
          rm -f /tmp/my-key.pem
