name: Deploy to Frontend EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: List build directory
        run: ls -la ./packages/frontend/build # Verify the build directory contents

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Save the SSH key to a temporary file
          echo "$SSH_KEY" > /tmp/my-key.pem
          chmod 600 /tmp/my-key.pem

          # Check if the build directory exists before transferring
          if [ -d "./packages/frontend/build" ]; then
            # Transfer files to the EC2 instance
            scp -o StrictHostKeyChecking=no -i /tmp/my-key.pem -r ./packages/frontend/build/* ec2-user@$INSTANCE_IP:/var/www/html/
          else
            echo "Build directory not found!"
            exit 1  # Exit with an error if the build directory does not exist
          fi

          # SSH into EC2 and restart Nginx
          ssh -o StrictHostKeyChecking=no -i /tmp/my-key.pem ec2-user@$INSTANCE_IP << 'EOF'
            # Debug: Check if you can connect
            whoami
            sudo systemctl restart nginx
          EOF

          # Cleanup
          rm /tmp/my-key.pem
