name: Deploy to Frontend EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: List build directory
        run: ls -la ./packages/frontend/dist # Verify the build directory contents

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # Save the SSH key to a temporary file
          echo "$SSH_KEY" > /tmp/my-key.pem
          chmod 600 /tmp/my-key.pem

          # Check if build directory exists
          if [ -d "./packages/frontend/dist" ]; then
            # Copy files to a temporary location first
            scp -o StrictHostKeyChecking=no -i /tmp/my-key.pem -r ./packages/frontend/dist/* ec2-user@$INSTANCE_IP:/home/ec2-user/deployment/
          else
            echo "Build directory not found!"
            exit 1
          fi

          # SSH into EC2 to move files with sudo
          ssh -o StrictHostKeyChecking=no -i /tmp/my-key.pem ec2-user@$INSTANCE_IP << 'EOF'
            sudo mv /home/ec2-user/deployment/* /var/www/html/
            sudo systemctl restart nginx
            sudo pm2 restart all
          EOF

          # Cleanup
          rm /tmp/my-key.pem
